export enum ErrorCodes {
	METHOD_NOT_ALLOWED = 'METHOD_NOT_ALLOWED',
	INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
	NOT_FOUND = 'NOT_FOUND',
	BAD_REQUEST = 'BAD_REQUEST',
	UNAUTHORIZED = 'UNAUTHORIZED',
	FORBIDDEN = 'FORBIDDEN',
	FILE_TOO_LARGE = 'FILE_TOO_LARGE',
}
